# PermissionsBukkit configuration file
# 
# A permission node is a string like 'permissions.build', usually starting
# with the name of the plugin. Refer to a plugin's documentation for what
# permissions it cares about. Each node should be followed by true to grant
# that permission or false to revoke it, as in 'permissions.build: true'.
# Some plugins provide permission nodes that map to a group of permissions -
# for example, PermissionsBukkit has 'permissions.*', which automatically
# grants all admin permissions. You can also specify false for permissions
# of this type.
# 
# Users inherit permissions from the groups they are a part of. If a user is
# not specified here, or does not have a 'groups' node, they will be in the
# group 'default'. Permissions for individual users may also be specified by
# using a 'permissions' node with a list of permission nodes, which will
# override their group permissions. World permissions may be assigned to
# users with a 'worlds:' entry.
# 
# Groups can be assigned to players and all their permissions will also be
# assigned to those players. Groups can also inherit permissions from other
# groups. Like user permissions, groups may override the permissions of their
# parent group(s). Unlike users, groups do NOT automatically inherit from
# default. World permissions may be assigned to groups with a 'worlds:' entry.
users:
  unDead_Herbs:
    groups:
    - admin
    - scrod
    - nyan
    - corner
    - mncht
  pagal196:
    groups:
    - corner
  PureZaros:
    groups:
    - scrod
    - corner
  qrrb:
    groups:
    - scrod
  leirbag_nosinbor:
    groups:
    - corner
  tinyxerica:
    groups:
    - mncht
  default:
    permissions:
      permissions.build: false
      multiverse.core.spawn.self: true
      multiverse.portal.access.*: true
  user:
    permissions:
      permissions.*: true
      multiverse.core.spawn.self: true
      multiverse.teleport.self.*: true
      multiverse.portal.access.*: true
      minecraft.command.tell: true
      minecraft.command.kill: true
      minecraft.command.me: true
      minecraft.command.tp: true
      multiverse.access.world: true
      multiverse.access.redstone: true
  scrod:
    inheritance:
    - user
    worlds:
      world:
        permissions.build: true
  widfam:
    inheritance:
    - user
    worlds:
      world:
        permissions.build: true
  corner:
    inheritance:
    - user
    worlds:
      world:
        permissions.build: true
  nyan:
    inheritance:
    - user
    worlds:
      world:
        permissions.build: true
      aeterna:
        permissions.build: true
  mncht:
    inheritance:
    - user
    worlds:
      world:
        permissions.build: true
      Island:
        permissions.build: true
  admin:
    inheritance:
    - user
    permissions:
      permissions.*: true
      multiverse.*: true
      pTweaks.*: true
      runecraft.*: true
      protocol.admin: true
      minecraft.command.*: true
      bukkit.command.*: true
      epicglass.*: true
  3caf52ec-f18f-4224-ac3f-20a4734a983e:
    groups:
    - scrod
    - corner
    - mncht
    - nyan
  5ecffea5-477a-47e1-b907-ff29d7073b42:
    groups:
    - scrod
  ada4058b-1709-4c70-8089-489e240c5973:
    groups:
    - corner
  51fdd8d0-965a-48c4-85a6-3969bf3db260:
    groups:
    - mncht
  0c47e8b9-eaa5-41bd-943c-239df8806e72:
    groups:
    - scrod
    - corner
  07ca06ff-0d15-4eaa-85be-a6d3519edc0f:
    groups:
    - admin
  f6bd0935-35a7-4931-9ea3-90c3ea360237:
    groups:
    - scrod
  1e96be40-ba8f-4df5-bbc2-e45af7c6eda3:
    groups:
    - nyan
  7bb29fd2-0f60-4b67-803b-adc35f384830:
    groups:
    - widfam
  fa7d66cd-3ba4-4da9-b9d0-5b47f28d3c49:
    groups:
    - nyan
  275c814e-43fc-447d-a1f3-ba1de7995ff3:
    groups:
    - scrod
messages:
  build: '&cYou do not have permission to build here.'
debug: false
